### PR TITLE
Github oauth added ( to avoid the spam contents )

### PR DESCRIPTION
**Pull request by imanaspaul**

### CODE REVIEW

**Comment by ykdojo** [comment]
Hi, I just wanted to let you know that I haven't forgotten about this. I was just making some other changes today.

**Comment by ykdojo** [comment]
FYI: I'm thinking of working on this issue first because it seems somewhat serious: https://github.com/ykdojo/csqa/issues/2

**Comment by imanaspaul** [comment]
I have implemented github oauth so I think that would be better not using the custom signup process, cause with custom one anyone can join to he server and spread spam

**Comment by pyanishjain** [comment]
> I have implemented github oauth so I think that would be better not using the custom signup process, cause with custom one anyone can join to he server and spread spam

is is also possible to google authentication it is also helpful if it is then how

**Comment by imanaspaul** [comment]
> > I have implemented github oauth so I think that would be better not using the custom signup process, cause with custom one anyone can join to he server and spread spam
> 
> is is also possible to google authentication it is also helpful if it is then how

Yes, you could implement that easily, check out the documentation of Django-allauth

**Pull request closed without merging**
